[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/moonfly.toml"]

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14
builtin_box_drawing = true

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[window]
opacity = 1
decorations = "Full"
dynamic_title = true
dynamic_padding = false

[window.padding]
x = 2
y = 0
